# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor_A = torch.rand(7, 7)
random_tensor_A

tensor([[0.4204, 0.2248, 0.1619, 0.2421, 0.7301, 0.7392, 0.7691],
        [0.3417, 0.8604, 0.5585, 0.4934, 0.7569, 0.0729, 0.1845],
        [0.2185, 0.4811, 0.9754, 0.4023, 0.3033, 0.4041, 0.4795],
        [0.9483, 0.6407, 0.4192, 0.6266, 0.2056, 0.8312, 0.7216],
        [0.0588, 0.6336, 0.1824, 0.4238, 0.2562, 0.6604, 0.7394],
        [0.5213, 0.5636, 0.1455, 0.2653, 0.3798, 0.4617, 0.6071],
        [0.9294, 0.4609, 0.7980, 0.9764, 0.0020, 0.3250, 0.2502]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor_B = torch.rand(1, 7)
# Perform matrix multiplication
torch.matmul(random_tensor_A, random_tensor_B.T)

tensor([[1.8190],
        [1.7409],
        [1.9008],
        [2.2681],
        [1.7015],
        [1.4955],
        [2.1170]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_A = torch.rand(7, 7)
random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
output = torch.matmul(random_tensor_A, random_tensor_B.T)
output, output.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
random_tensor_A = torch.rand(2, 3).to("cuda")
random_tensor_B = torch.rand(2, 3).to("cuda")

print(f"Device: {random_tensor_A.device.type}")
random_tensor_A, random_tensor_B



Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(random_tensor_A, random_tensor_B.T)
output, output.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(f"Maximum: {output.max()}")
# Find min
print(f"Minimum: {output.min()}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(f"Maximum index value: {output.argmax()}")

# Find arg min
print(f"Minimum index value: {output.argmin()}")

Maximum index value: 3
Minimum index value: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_x = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_x_reshaped = random_tensor_x.reshape(10)

# Print out tensors and their shapes
print(random_tensor_x, random_tensor_x.shape)
print(random_tensor_x_reshaped, random_tensor_x_reshaped.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
